apiVersion: v1
kind: Service
metadata:
  labels:
    app: ui-vuejs
  name: ui-vuejs
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: ui-vuejs
status:
  loadBalancer: {}
